# Generated by Django 2.2.14 on 2020-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leavewordreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveword',
            name='zan_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='leavewordreply',
            name='zan_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='topic',
            name='reply_num',
            field=models.IntegerField(default=0, verbose_name='回复数量'),
        ),
    ]
