# Generated by Django 2.2.14 on 2020-07-21 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200721_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveWordZan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LeaveWord', verbose_name='留言')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '留言点赞',
            },
        ),
        migrations.CreateModel(
            name='LeaveWordReplyZan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_word_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LeaveWordReply', verbose_name='留言回复')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '留言回复点赞',
            },
        ),
    ]
